"""Třetí dávka rodin pro Vetřelce.

Novinka proti prvním dvěma: `loose` — zavádějící věty, které **neplatí pro
všech pět slov**. U každé je vypsáno, na koho sedí, a generátor ji do
nabídky pustí jen tehdy, když v dané pětici neplatí pro právě čtyři.
Tři ze čtyř nebo dva z pěti nevydělují nikoho, takže hádanku nerozbijí —
zato nutí hráče věty doopravdy zvažovat, ne je odškrtávat podle toho, že
„platí pro všechny, tak to nebude ono".
"""

EXTRA3 = [
    {
        "id": "hory-vysoke",
        "roof": "hory a pohoří",
        "level": "hard",
        "inside": ["Sněžka", "Praděd", "Lysá hora", "Radhošť", "Ještěd", "Milešovka",
                   "Boubín", "Klínovec", "Kralický Sněžník", "Javorník"],
        "outside": ["Mont Blanc", "Matterhorn", "Etna", "Grossglockner", "Triglav",
                    "Gerlach", "Rysy", "Fudži", "Olymp"],
        "asks": ["leží v Česku", "jsou to hory", "dá se na ně vyjít pěšky",
                 "mají vrchol nad lesem", "jsou vidět z dálky", "jezdí k nim turisté"],
    },
    {
        "id": "psi-plemena",
        "roof": "psí plemena",
        "level": "normal",
        "inside": ["jezevčík", "border kolie", "ovčák", "retrívr", "pudl", "chrt",
                   "husky", "beagle", "dalmatin", "špic"],
        "outside": ["mainská mývalí", "perská", "ragdoll", "britská krátkosrstá",
                    "siamská", "habešská"],
        "asks": ["jsou to psi", "chovají je lidé doma", "mají srst",
                 "existuje pro ně chovatelský standard", "dá se je cvičit", "žijí i deset let"],
    },
    {
        "id": "barvy-zakladni",
        "roof": "barvy",
        "level": "easy",
        "inside": ["červená", "modrá", "žlutá", "zelená", "oranžová", "fialová"],
        "outside": ["bílá", "černá", "šedá", "béžová", "hnědá", "stříbrná", "zlatá"],
        "asks": ["najdeš je v duze", "je to barva", "dá se namíchat z barviv",
                 "používá se v malbě", "má svoje jméno", "vidí ji lidské oko"],
        "loose": [
            {"text": "bývají na dopravních značkách",
             "words": ["červená", "modrá", "žlutá", "zelená", "bílá", "černá"]},
            {"text": "objevují se ve vlajkách států",
             "words": ["červená", "modrá", "žlutá", "zelená", "bílá", "černá", "oranžová"]},
        ],
    },
    {
        "id": "obchody-potraviny",
        "roof": "obchody a provozovny",
        "level": "normal",
        "inside": ["pekárna", "řeznictví", "cukrárna", "mlékárna", "ovoce a zelenina",
                   "lahůdky", "vinotéka", "rybárna"],
        "outside": ["knihkupectví", "papírnictví", "drogerie", "lékárna", "hodinářství",
                    "květinářství", "železářství", "optika"],
        "asks": ["prodávají jídlo nebo pití", "je to obchod", "mají otevírací dobu",
                 "obsluhuje v nich prodavač", "najdeš je ve městě", "platí se v nich"],
    },
    {
        "id": "hmyz-krídla",
        "roof": "hmyz a drobní živočichové",
        "level": "hard",
        "inside": ["včela", "vosa", "moucha", "motýl", "vážka", "komár", "brouk",
                   "cvrček", "mšice", "chrousta"],
        "outside": ["pavouk", "štír", "klíště", "roztoč", "stonožka", "žížala",
                    "slimák", "sekáč"],
        "asks": ["patří mezi hmyz", "jsou to drobní živočichové", "mají článkované tělo",
                 "žijí i u nás", "můžeš je potkat na zahradě", "rozmnožují se vajíčky"],
        "loose": [
            {"text": "umějí létat",
             "words": ["včela", "vosa", "moucha", "motýl", "vážka", "komár", "brouk", "chrousta"]},
        ],
    },
    {
        "id": "napoje-kofein",
        "roof": "nápoje",
        "level": "normal",
        "inside": ["káva", "espresso", "černý čaj", "zelený čaj", "kola", "maté",
                   "energetický nápoj"],
        "outside": ["mléko", "voda", "limonáda", "džus", "kakao", "bylinkový čaj",
                    "sirup", "minerálka"],
        "asks": ["obsahují kofein", "dají se pít", "podávají se v kavárnách i doma",
                 "prodávají se v obchodě", "hodí se k snídani", "dají se pít teplé i studené"],
    },
    {
        "id": "svet-jazyky",
        "roof": "jazyky",
        "level": "hard",
        "inside": ["čeština", "polština", "slovenština", "ruština", "chorvatština",
                   "bulharština", "srbština", "ukrajinština", "slovinština"],
        "outside": ["němčina", "angličtina", "francouzština", "maďarština", "finština",
                    "italština", "rumunština", "španělština"],
        "asks": ["jsou to slovanské jazyky", "mluví se jimi v Evropě", "mají vlastní gramatiku",
                 "dají se studovat", "píší se abecedou", "mají miliony mluvčích"],
    },
    {
        "id": "domacnost-elektro",
        "roof": "věci v domácnosti",
        "level": "easy",
        "inside": ["lednice", "pračka", "myčka", "trouba", "mikrovlnka", "vysavač",
                   "fén", "žehlička", "toustovač"],
        "outside": ["koberec", "polštář", "závěs", "zrcadlo", "váza", "koš",
                    "věšák", "polička", "deka"],
        "asks": ["potřebují elektřinu", "patří do domácnosti", "dají se koupit v obchodě",
                 "vydrží roky", "mají svoje místo v bytě", "vyrábí je továrna"],
    },
    {
        "id": "cesky-hrad",
        "roof": "české hrady a zámky",
        "level": "hard",
        "inside": ["Karlštejn", "Křivoklát", "Bezděz", "Kokořín", "Rabí", "Trosky",
                   "Zvíkov", "Pernštejn"],
        "outside": ["Hluboká", "Lednice", "Český Krumlov", "Kroměříž", "Valtice",
                    "Konopiště", "Průhonice", "Slavkov"],
        "asks": ["jsou to hrady, ne zámky", "stojí v Česku", "jsou přístupné veřejnosti",
                 "pocházejí ze středověku nebo novověku", "jezdí k nim turisté",
                 "objevují se na fotografiích Česka"],
    },
    {
        "id": "hudba-zanry",
        "roof": "hudební žánry",
        "level": "normal",
        "inside": ["rock", "pop", "jazz", "blues", "hip hop", "metal", "punk", "funk"],
        "outside": ["opera", "symfonie", "chorál", "kantáta", "sonáta", "oratorium",
                    "koncert", "árie"],
        "asks": ["patří k populární hudbě", "je to hudební žánr", "poslouchají ho lidé",
                 "hraje se na koncertech", "nahrává se do alb", "má svoje typické nástroje"],
    },
    {
        "id": "telo-smysly",
        "roof": "části těla",
        "level": "normal",
        "inside": ["oko", "ucho", "nos", "jazyk", "kůže"],
        "outside": ["loket", "koleno", "pata", "rameno", "prst", "brada", "zápěstí",
                    "kotník", "lopatka"],
        "asks": ["slouží ke smyslovému vnímání", "jsou to části lidského těla",
                 "má je každý", "dají se ukázat na sobě", "mají je i zvířata",
                 "zkoumá je lékař"],
    },
    {
        "id": "zeme-ostrovy",
        "roof": "země světa",
        "level": "hard",
        "inside": ["Island", "Kuba", "Kypr", "Madagaskar", "Nový Zéland", "Japonsko",
                   "Srí Lanka", "Malta", "Irsko", "Jamajka"],
        "outside": ["Norsko", "Mexiko", "Egypt", "Chile", "Turecko", "Vietnam",
                    "Portugalsko", "Peru", "Maroko"],
        "asks": ["leží celé na ostrově nebo ostrovech", "jsou to samostatné státy",
                 "mají vlastní vlajku", "leží u moře", "mají hlavní město",
                 "jsou členy OSN"],
    },
    {
        "id": "nastroje-mereni",
        "roof": "přístroje",
        "level": "normal",
        "inside": ["teploměr", "tlakoměr", "vlhkoměr", "výškoměr", "rychloměr",
                   "voltmetr", "hustoměr", "váha"],
        "outside": ["dalekohled", "mikroskop", "lupa", "periskop", "fotoaparát",
                    "brýle", "zrcátko", "projektor"],
        "asks": ["něco měří a ukazují hodnotu", "je to přístroj", "vyrábějí se přesně",
                 "používají se v praxi i doma", "mají svoje jméno", "dají se koupit"],
    },
    {
        "id": "kniha-svetova",
        "roof": "slavné knihy",
        "level": "hard",
        "inside": ["Babička", "Máj", "Osudy dobrého vojáka Švejka", "R.U.R.",
                   "Krakatit", "Kytice", "Bílá nemoc", "Saturnin"],
        "outside": ["Hamlet", "Malý princ", "Robinson Crusoe", "Tři mušketýři",
                    "Vojna a mír", "Odysseia", "Bídníci", "Faust"],
        "asks": ["napsal je český autor", "jsou to knihy nebo hry", "čtou se dodnes",
                 "vyšly tiskem", "objevují se ve školní četbě", "mají hlavní postavu"],
    },
    {
        "id": "priroda-houby",
        "roof": "co roste v lese",
        "level": "normal",
        "inside": ["hřib", "křemenáč", "kozák", "liška", "bedla", "žampion",
                   "václavka", "muchomůrka", "klouzek"],
        "outside": ["borůvka", "malina", "ostružina", "brusinka", "jahoda", "kapradí",
                    "mech", "šípek", "bez"],
        "asks": ["jsou to houby", "roste to v lese", "sbírá se to na podzim nebo v létě",
                 "dá se to najít v Česku", "roste to při zemi", "chodí se na to s košíkem"],
    },
    {
        "id": "penize-mince",
        "roof": "české mince a bankovky",
        "level": "easy",
        "inside": ["koruna", "dvoukoruna", "pětikoruna", "desetikoruna", "dvacetikoruna",
                   "padesátikoruna"],
        "outside": ["stokoruna", "dvoustovka", "pětistovka", "tisícikoruna",
                    "dvoutisícovka", "pětitisícovka"],
        "asks": ["je to mince, ne bankovka", "platí se tím v Česku", "vydává to národní banka",
                 "má to svoji hodnotu", "vejde se to do peněženky", "používá se to denně"],
    },
    {
        "id": "sport-zimni",
        "roof": "olympijské sporty",
        "level": "normal",
        "inside": ["biatlon", "sjezdové lyžování", "krasobruslení", "curling",
                   "snowboarding", "boby", "skoky na lyžích", "rychlobruslení"],
        "outside": ["atletika", "plavání", "veslování", "judo", "šerm", "vzpírání",
                    "jachting", "lukostřelba"],
        "asks": ["patří na zimní olympiádu", "je to olympijský sport",
                 "soutěží se v něm o medaile", "má mistrovství světa", "trénuje se celoročně",
                 "mají ho v přenosu televize"],
    },
    {
        "id": "moda-latka",
        "roof": "textilie",
        "level": "hard",
        "inside": ["bavlna", "len", "vlna", "hedvábí", "konopí", "juta", "kašmír"],
        "outside": ["polyester", "nylon", "elastan", "viskóza", "akryl", "mikrovlákno",
                    "lycra", "polyamid"],
        "asks": ["je to přírodní vlákno", "šije se z toho oblečení", "prodává se to v metráži",
                 "dá se to obarvit", "vyrábí se z toho látka", "má to svoje typické vlastnosti"],
    },
    {
        "id": "kuchyne-mleko",
        "roof": "potraviny",
        "level": "normal",
        "inside": ["sýr", "jogurt", "tvaroh", "smetana", "máslo", "kefír", "podmáslí",
                   "zakysaná smetana"],
        "outside": ["chleba", "vejce", "med", "olej", "rýže", "mouka", "cukr",
                    "těstoviny", "sůl"],
        "asks": ["vyrábějí se z mléka", "jsou to potraviny", "prodávají se v obchodě",
                 "skladují se v kuchyni", "dají se použít při vaření", "mají trvanlivost"],
    },
    {
        "id": "voda-stojata",
        "roof": "vodní plochy a toky",
        "level": "easy",
        "inside": ["jezero", "rybník", "přehrada", "tůň", "laguna", "nádrž", "bazén"],
        "outside": ["řeka", "potok", "bystřina", "kanál", "vodopád", "pramen",
                    "říčka", "průplav"],
        "asks": ["voda v nich stojí, neteče", "je v nich voda", "dá se u nich sedět",
                 "objevují se na mapě", "dá se v nich za teplého počasí plavat",
                 "mají břeh"],
    },
]
