"""Čtvrtá dávka rodin pro Vetřelce.

Tvar i pravidla jako v předchozích dávkách. `loose` jsou věty, které
neplatí pro celou rodinu — generátor je pustí do nabídky, jen když
v dané pětici neplatí pro právě čtyři slova.
"""

EXTRA4 = [
    {
        "id": "zvirata-vejce",
        "roof": "živočichové",
        "level": "hard",
        "inside": ["slepice", "krokodýl", "želva", "had", "ještěrka", "žralok",
                   "pštros", "ptakopysk", "žába", "mravenec"],
        "outside": ["kráva", "kůň", "pes", "kočka", "velryba", "netopýr", "slon",
                    "myš", "opice", "delfín"],
        "asks": ["kladou vejce", "jsou to živočichové", "mají mláďata",
                 "žijí na Zemi", "dýchají", "dají se najít v zoo"],
        "loose": [
            {"text": "žijí ve vodě nebo u vody",
             "words": ["krokodýl", "želva", "žralok", "žába", "velryba", "delfín"]},
        ],
    },
    {
        "id": "nadobi-varime",
        "roof": "kuchyňské nádobí",
        "level": "normal",
        "inside": ["hrnec", "pánev", "kastrol", "wok", "papiňák", "kotlík", "rendlík"],
        "outside": ["talíř", "miska", "hrnek", "sklenice", "džbán", "podnos",
                    "salátová mísa", "šálek"],
        "asks": ["vaří se v tom na sporáku", "je to nádobí", "myje se to po jídle",
                 "vejde se to do kuchyňské linky", "má to svůj tvar a objem",
                 "dá se to koupit v obchodě"],
    },
    {
        "id": "kvetiny-cibule",
        "roof": "květiny",
        "level": "hard",
        "inside": ["tulipán", "narcis", "hyacint", "lilie", "šafrán", "česnek ozdobný",
                   "modřenec", "sněženka"],
        "outside": ["růže", "kopretina", "slunečnice", "chrpa", "pivoňka", "macešky",
                    "orchidej", "fialka"],
        "asks": ["rostou z cibule nebo hlízy", "jsou to květiny", "kvetou barevně",
                 "dají se pěstovat na zahradě", "prodávají se v květinářství",
                 "mají stonek a listy"],
    },
    {
        "id": "media-tisk",
        "roof": "sdělovací prostředky",
        "level": "normal",
        "inside": ["noviny", "časopis", "týdeník", "deník", "magazín", "bulletin",
                   "zpravodaj"],
        "outside": ["rozhlas", "televize", "podcast", "webová stránka", "vysílání",
                    "zpravodajský kanál", "sociální síť"],
        "asks": ["vychází to tištěné na papíře", "přináší to zprávy",
                 "má to redakci", "vychází to pravidelně", "dá se to předplatit",
                 "informuje to veřejnost"],
    },
    {
        "id": "tanec-parovy",
        "roof": "tance",
        "level": "normal",
        "inside": ["valčík", "tango", "polka", "waltz", "foxtrot", "cha-cha",
                   "rumba", "jive"],
        "outside": ["balet", "step", "breakdance", "sólový tanec", "moderna",
                    "flamenco", "hip hop", "irský tanec"],
        "asks": ["tančí se ve dvojici", "je to tanec", "tančí se na hudbu",
                 "dá se to naučit v kurzu", "má to svoje kroky", "tančí se to na parketu"],
    },
    {
        "id": "vlastnosti-dobre",
        "roof": "lidské vlastnosti",
        "level": "hard",
        "inside": ["poctivost", "štědrost", "trpělivost", "odvaha", "skromnost",
                   "věrnost", "pracovitost", "laskavost"],
        "outside": ["lakota", "závist", "pýcha", "lenost", "hněv", "zbabělost",
                    "chamtivost", "zlomyslnost"],
        "asks": ["je to dobrá vlastnost", "je to lidská vlastnost",
                 "dá se to na někom poznat", "mluví se o tom v pohádkách",
                 "má to svoje jméno v češtině", "týká se to povahy"],
    },
    {
        "id": "obchod-nabytek",
        "roof": "místnosti v domě",
        "level": "easy",
        "inside": ["kuchyň", "koupelna", "ložnice", "obývák", "dětský pokoj",
                   "pracovna", "jídelna", "předsíň"],
        "outside": ["balkon", "terasa", "dvůr", "zahrada", "garáž", "půda",
                    "sklep", "veranda"],
        "asks": ["je to obytná místnost uvnitř", "patří to k domu nebo bytu",
                 "má to podlahu", "dá se tam vejít", "má to svoje jméno",
                 "bývá to na plánku bytu"],
    },
    {
        "id": "voda-skupenstvi",
        "roof": "podoby vody",
        "level": "hard",
        "inside": ["led", "sníh", "jinovatka", "kroupy", "námraza", "ledovec"],
        "outside": ["pára", "mlha", "rosa", "déšť", "mrholení", "oblak", "vlhkost"],
        "asks": ["je to voda v pevném stavu", "je to podoba vody",
                 "objevuje se to v přírodě", "závisí to na teplotě",
                 "dá se to vidět", "zmiňuje to předpověď počasí"],
    },
    {
        "id": "sport-rakety",
        "roof": "sporty",
        "level": "normal",
        "inside": ["tenis", "badminton", "squash", "stolní tenis", "padel",
                   "raketbal"],
        "outside": ["fotbal", "volejbal", "házená", "basketbal", "ragby",
                    "vodní pólo", "florbal", "hokej"],
        "asks": ["hraje se s raketou nebo pálkou", "je to míčový sport",
                 "hraje se na hřišti nebo kurtu", "má to pravidla a rozhodčího",
                 "existuje k tomu mistrovství", "hrají to i amatéři"],
    },
    {
        "id": "prace-zvire",
        "roof": "zvířata chovaná lidmi",
        "level": "hard",
        "inside": ["kráva", "koza", "ovce", "prase", "slepice", "husa", "kachna",
                   "králík", "kůň", "včela"],
        "outside": ["pes", "kočka", "morče", "křeček", "andulka", "papoušek",
                    "želva", "akvarijní rybka", "činčila"],
        "asks": ["chovají se pro užitek", "chová je člověk", "žijí u lidských obydlí",
                 "mají svoje jméno v češtině", "krmí je hospodář nebo majitel",
                 "objevují se v pohádkách"],
    },
    {
        "id": "pismo-abeceda",
        "roof": "písma a abecedy",
        "level": "hard",
        "inside": ["latinka", "cyrilice", "řecká alfabeta", "hebrejské písmo",
                   "arabské písmo", "hlaholice"],
        "outside": ["hieroglyfy", "klínové písmo", "čínské znaky", "japonská kandži",
                    "mayské písmo", "runové znaky"],
        "asks": ["používá se dodnes", "je to písmo", "zapisují se jím slova",
                 "má to svoje znaky", "psalo se tím po staletí", "zkoumají to badatelé"],
    },
    {
        "id": "obchod-sluzby",
        "roof": "provozovny a služby",
        "level": "normal",
        "inside": ["kadeřnictví", "holičství", "kosmetika", "manikúra", "masáže",
                   "pedikúra", "solárium"],
        "outside": ["opravna", "autoservis", "čistírna", "zámečnictví", "pneuservis",
                    "kopírka", "sklenářství"],
        "asks": ["pečuje to o tělo a vzhled", "je to služba", "objednává se to předem",
                 "platí se to po vykonání", "má to otevírací dobu",
                 "pracuje tam vyučený člověk"],
    },
    {
        "id": "mesto-cesko",
        "roof": "česká města",
        "level": "hard",
        "inside": ["Praha", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc",
                   "České Budějovice", "Hradec Králové", "Ústí nad Labem", "Pardubice"],
        "outside": ["Tábor", "Kutná Hora", "Telč", "Litomyšl", "Krumlov", "Třeboň",
                    "Slavonice", "Mikulov", "Loket"],
        "asks": ["má přes sto tisíc obyvatel", "je to české město",
                 "má vlastní radnici", "leží v Česku", "jezdí tam vlak",
                 "objevuje se na mapě"],
    },
    {
        "id": "nastroj-klavesy",
        "roof": "hudební nástroje",
        "level": "normal",
        "inside": ["klavír", "varhany", "cembalo", "harmonium", "akordeon",
                   "klávesy", "celesta"],
        "outside": ["kytara", "housle", "trubka", "buben", "flétna", "harfa",
                    "saxofon", "kontrabas"],
        "asks": ["hraje se na to pomocí kláves", "je to hudební nástroj",
                 "vydává to tóny", "hraje na to hudebník", "dá se to naučit",
                 "objevuje se to v koncertním sále"],
    },
    {
        "id": "cesta-znacky",
        "roof": "dopravní značky a prvky",
        "level": "normal",
        "inside": ["stopka", "zákaz vjezdu", "přednost v jízdě", "zákaz stání",
                   "omezená rychlost", "zákaz předjíždění"],
        "outside": ["přechod pro chodce", "parkoviště", "nemocnice", "informace",
                    "objížďka", "dálnice", "obytná zóna"],
        "asks": ["něco to zakazuje nebo přikazuje", "je to dopravní značka",
                 "stojí to u silnice", "řídí se tím řidiči",
                 "má to svůj tvar a barvu", "učí se to v autoškole"],
    },
    {
        "id": "priroda-savci-let",
        "roof": "savci",
        "level": "hard",
        # Poddruhy jednoho netopýra tu stály zbytečně: do jedné pětice se
        # čtyři z nich nevejdou, aniž by dvě byla „netopýr něco", a to
        # vypadá jako přehlédnutí. Létajících savců je málo, takže rodina
        # má přesně čtyři slova a každé jiné.
        "inside": ["netopýr", "kaloň", "vrápenec", "upír"],
        "outside": ["veverka", "kuna", "liška", "jezevec", "myš", "krtek",
                    "ježek", "rys", "zajíc", "srnec"],
        "asks": ["umí aktivně létat", "je to savec", "žije v Evropě",
                 "má srst", "rodí živá mláďata", "dá se potkat v přírodě"],
    },
    {
        "id": "jidlo-polevka",
        "roof": "česká jídla",
        "level": "easy",
        "inside": ["gulášovka", "bramboračka", "česnečka", "zelňačka", "kulajda",
                   "dršťková", "hrachová polévka"],
        "outside": ["svíčková", "guláš", "řízek", "vepřo knedlo zelo", "smažený sýr",
                    "buchtičky", "koprovka", "rajská"],
        "asks": ["je to polévka", "je to české jídlo", "vaří se to v hrnci",
                 "podává se to teplé", "najdeš to na jídelním lístku",
                 "jí se to lžící nebo příborem"],
    },
    {
        "id": "svet-poust",
        "roof": "místa na Zemi",
        "level": "hard",
        "inside": ["Sahara", "Gobi", "Kalahari", "Atacama", "Namib", "Karakum"],
        "outside": ["Amazonie", "Sibiř", "Aljaška", "Patagonie", "Skandinávie",
                    "Balkán", "Kavkaz", "Ural"],
        "asks": ["je to poušť", "je to velká oblast na mapě", "má to svoje jméno",
                 "leží to na jednom kontinentu", "jezdí tam výpravy",
                 "objevuje se to v zeměpisu"],
    },
    {
        "id": "obleceni-spodni",
        "roof": "oblečení",
        "level": "normal",
        "inside": ["kalhoty", "sukně", "šortky", "legíny", "tepláky", "kraťasy",
                   "džíny"],
        "outside": ["košile", "tričko", "svetr", "mikina", "sako", "halenka",
                    "vesta", "bunda"],
        "asks": ["nosí se to na dolní polovině těla", "je to oblečení",
                 "má to velikosti", "kupuje se to v obchodě", "pere se to",
                 "nosí to muži i ženy"],
    },
]
