"""Druhá dávka rodin pro Vetřelce a rozšíření té první.

`MORE` doplňuje slova do už napsaných rodin — víc členů znamená víc
různých pětic z téže rodiny. `EXTRA` jsou rodiny nové. Tvar i pravidla
jsou stejné jako v `intruder_families.py`.
"""

# Doplňky do rodin první dávky, podle jejich `id`.
MORE = {
    "voda-sladka": {
        "inside": ["parma", "jelec", "plotice", "karas", "ježdík", "mník", "rybenka",
                   "nutrie", "ondatra", "pijavice", "larva jepice", "škeble rybničná"],
        "outside": ["mořský ježek", "hvězdice", "murény", "sépie", "krevety", "mrož",
                    "lachtan", "manta", "korál", "humr"],
    },
    "auto-vybava": {
        "inside": ["motor", "chladič", "startér", "tlumič", "poloosa", "palivoměr",
                   "blinkr", "podběh", "loketní opěrka", "palubní deska"],
        "outside": ["mobil", "nabíječka", "brýle", "parkovací lístek", "kufr",
                    "hasicí přístroj", "vlečné lano", "sněhové řetězy"],
    },
    "nastroje-smycce": {
        "inside": ["fidula", "rebek", "kobyz"],
        "outside": ["balalajka", "sitár", "cembalo", "harmonika", "koto", "domra"],
    },
    "koreni-semena": {
        "inside": ["hřebíček", "nové koření", "sezam", "mák", "pískavice", "sumak",
                   "zázvor", "kurkuma"],
        "outside": ["saturejka", "dobromysl", "meduňka", "estragon", "pažitka",
                    "bobkový list", "koriandrová nať"],
    },
    "sporty-mic": {
        "inside": ["squash", "badminton", "stolní tenis", "vodní pólo", "korfbal",
                   "lakros", "petanque", "golf"],
        "outside": ["šipky", "šachy", "zápas", "gymnastika", "triatlon", "skoky na lyžích",
                    "biatlon", "kanoistika", "surfing"],
    },
    "kov-drahy": {
        "inside": ["osmium", "ruthenium"],
        "outside": ["wolfram", "mangan", "kobalt", "vanad", "molybden", "sodík",
                    "draslík", "vápník"],
    },
    "mesta-more": {
        "inside": ["Kodaň", "Podgorica", "Nikósie", "Monako", "Londýn", "Řím"],
        "outside": ["Lublaň", "Záhřeb", "Skopje", "Kišiněv", "Vaduz", "Sarajevo",
                    "Bukurešť", "Vilnius", "Andorra la Vella"],
    },
    "babicka-postavy": {
        "inside": ["Jan Prošek", "Terezka", "Vilém", "myslivec", "Sultán", "Tyrl"],
        "outside": ["Rychlé šípy", "Lucie", "Vávra", "Kristián", "Ferda Mravenec"],
    },
    "stromy-jehlicnany": {
        "inside": ["borovice černá", "smrk pichlavý", "jedle bělokorá", "kleč", "tuje"],
        "outside": ["akát", "platan", "jeřáb", "třešeň", "hrušeň", "oskeruše",
                    "líska", "bez černý"],
    },
    "kuchyne-rez": {
        "inside": ["hoblík na sýr", "vykrajovátko", "kolečko na pizzu", "loupač"],
        "outside": ["šlehač", "trychtýř", "kuchyňské kleště", "sítko", "váleček",
                    "mlýnek", "otvírák", "stěrka"],
    },
    "staty-bezmore": {
        "inside": ["Kosovo", "San Marino", "Vatikán", "Lucembursko"],
        "outside": ["Švédsko", "Dánsko", "Španělsko", "Francie", "Německo", "Ukrajina",
                    "Bulharsko", "Lotyšsko", "Litva", "Island"],
    },
    "ptaci-nelet": {
        "inside": ["tučňák císařský", "pštros dvouprstý", "kivi hnědý", "kachna pižmová"],
        "outside": ["holub", "havran", "straka", "kachna", "husa", "bažant",
                    "koroptev", "poštolka", "ledňáček", "brhlík"],
    },
    "hodiny-cas": {
        "inside": ["kukačky", "kapesní hodinky", "vodní hodiny", "atomové hodiny",
                   "časovač", "kyvadlo"],
        "outside": ["pravítko", "svinovací metr", "krokoměr", "sonda", "dozimetr",
                    "voltmetr", "ampérmetr", "hustoměr"],
    },
    "zelenina-koren": {
        "inside": ["česnek", "cibule", "pórek", "batáty", "jicama", "černý kořen",
                   "ředkev", "petržel kořenová"],
        "outside": ["květák", "kapusta", "zelí", "špenát", "salát", "chřest",
                    "artyčok", "rebarbora", "hrášek"],
    },
    "budovy-vira": {
        "inside": ["basilika", "rotunda", "pagoda", "svatyně", "poutní kostel"],
        "outside": ["kino", "banka", "pošta", "věznice", "sklad", "hotel",
                    "obchodní dům", "sokolovna", "sportovní hala"],
    },
    "nemoci-virus": {
        "inested": [],
        "inside": ["příušnice", "plané neštovice", "zarděnky", "covid", "ebola",
                   "žlutá zimnice", "dengue"],
        "outside": ["zápal plic", "úplavice", "kapavka", "spála", "malárie",
                    "listerióza", "brucelóza"],
    },
    "napoje-kvaseni": {
        "inside": ["burčák", "cidre", "perry", "kombucha", "kefír"],
        "outside": ["mošt", "sodovka", "tonik", "energetický nápoj", "ovocný čaj",
                    "horká čokoláda", "smoothie"],
    },
    "mesice-31": {
        "inside": [],
        "outside": [],
    },
    "sachy-figury": {
        "inside": [],
        "outside": [],
    },
    "planety-kamenne": {
        "inside": [],
        "outside": [],
    },
}

EXTRA = [
    {
        "id": "hudba-dechy",
        "roof": "hudební nástroje",
        "level": "normal",
        "inside": ["flétna", "klarinet", "hoboj", "fagot", "trubka", "pozoun",
                   "lesní roh", "saxofon", "tuba", "pikola", "zobcová flétna"],
        "outside": ["buben", "činely", "triangl", "xylofon", "tympány", "marimba",
                    "kastaněty", "tamburína"],
        "asks": ["hraje se na ně dechem", "hrají v dechovce", "vyrábějí se z kovu nebo dřeva"],
    },
    {
        "id": "reky-cesko",
        "roof": "řeky",
        "level": "hard",
        "inside": ["Vltava", "Labe", "Morava", "Sázava", "Berounka", "Ohře", "Dyje",
                   "Otava", "Jizera", "Lužnice", "Svratka", "Odra"],
        "outside": ["Seina", "Temže", "Rýn", "Dunaj", "Pád", "Ebro", "Visla",
                    "Loira", "Tibera", "Něva"],
        "asks": ["protékají Českem", "jsou to řeky", "vlévají se nakonec do moře"],
    },
    {
        "id": "obleceni-hlava",
        "roof": "oblečení a doplňky",
        "level": "easy",
        "inside": ["klobouk", "čepice", "šátek", "helma", "baret", "kšiltovka",
                   "kapuce", "turban", "cylindr", "čelenka"],
        "outside": ["rukavice", "šála", "ponožky", "opasek", "kravata", "sako",
                    "sukně", "boty", "vesta", "kabát"],
        "asks": ["nosí se na hlavě", "jsou to kusy oblečení", "chrání před chladem"],
    },
    {
        "id": "nabytek-sezeni",
        "roof": "nábytek",
        "level": "easy",
        "inside": ["židle", "křeslo", "lavice", "pohovka", "taburet", "stolička",
                   "houpací křeslo", "sedačka"],
        "outside": ["stůl", "skříň", "police", "komoda", "postel", "věšák",
                    "psací stůl", "knihovna", "truhla"],
        "asks": ["sedá se na ně", "je to nábytek", "bývají dřevěné"],
    },
    {
        "id": "zvirata-nocni",
        "roof": "zvířata žijící v Česku",
        "level": "hard",
        "inside": ["sova", "netopýr", "jezevec", "kuna", "ježek", "výr", "plch",
                   "liška", "rys", "vydra"],
        "outside": ["veverka", "srnec", "zajíc", "bažant", "skřivan", "čáp",
                    "krtek", "sýkora", "vlaštovka", "motýl"],
        "asks": ["loví a pohybují se v noci", "žijí volně v Česku", "jsou to obratlovci"],
    },
    {
        "id": "ovoce-jadrove",
        "roof": "ovoce",
        "level": "normal",
        "inside": ["jablko", "hruška", "kdoule", "mišpule", "jeřabina", "muchovník"],
        "outside": ["švestka", "třešeň", "meruňka", "broskev", "višeň", "mango",
                    "olivy", "datle", "avokádo"],
        "asks": ["mají jádřinec s jadérky", "je to ovoce", "rostou na stromě"],
    },
    {
        "id": "svaty-podzim",
        "roof": "svátky slavené v Česku",
        "level": "normal",
        "inside": ["Vánoce", "Silvestr", "Mikuláš", "Dušičky", "Advent", "svatý Martin",
                   "Štědrý den", "Nový rok"],
        "outside": ["Velikonoce", "Letnice", "pálení čarodějnic", "Filipojakubská noc",
                    "svátek matek", "Den dětí", "svatba"],
        "asks": ["připadají na zimní půlku roku", "slaví se v Česku", "mají svoje zvyky"],
    },
    {
        "id": "obuv-zimni",
        "roof": "obuv",
        "level": "normal",
        "inside": ["holínky", "sněhule", "kanady", "kozačky", "bagančata", "válenky"],
        "outside": ["sandály", "žabky", "tenisky", "lodičky", "mokasíny", "espadrilky",
                    "baleríny", "pantofle"],
        "asks": ["hodí se do zimy a mokra", "obouvají se na nohy", "prodávají se v párech"],
    },
    {
        "id": "budovy-vysoke",
        "roof": "stavby",
        "level": "normal",
        "inside": ["věž", "rozhledna", "maják", "minaret", "komín", "mrakodrap",
                   "vodojem", "stožár"],
        "outside": ["most", "tunel", "hráz", "přehrada", "podchod", "hangár",
                    "stodola", "garáž", "plot"],
        "asks": ["jsou výrazně vyšší než širší", "postavil je člověk", "bývají z cihel nebo betonu"],
    },
    {
        "id": "prace-ruce",
        "roof": "řemesla a povolání",
        "level": "hard",
        "inside": ["truhlář", "zedník", "kovář", "švadlena", "hrnčíř", "sklář",
                   "klempíř", "pekař", "obuvník", "kameník"],
        "outside": ["účetní", "právník", "učitel", "lékař", "novinář", "pilot",
                    "policista", "překladatel", "programátor", "herec"],
        "asks": ["vyrábějí něco rukama", "je to povolání", "dá se to vyučit"],
    },
    {
        "id": "obraz-cesko",
        "roof": "světoznámé stavby",
        "level": "easy",
        "inside": ["Karlův most", "Pražský hrad", "Karlštejn", "Petřínská rozhledna",
                   "Staroměstský orloj", "Křivoklát", "Špilberk"],
        "outside": ["Eiffelovka", "Koloseum", "Akropole", "Big Ben", "Kreml",
                    "Sagrada Família", "Pyramidy", "Tower Bridge"],
        "asks": ["stojí v Česku", "jsou to známé stavby", "chodí se na ně dívat turisté"],
    },
    {
        "id": "materialy-prirodni",
        "roof": "materiály",
        "level": "normal",
        "inside": ["dřevo", "vlna", "bavlna", "len", "kůže", "hedvábí", "korek",
                   "kámen", "sláma", "kaučuk"],
        "outside": ["plast", "nylon", "polyester", "sklolaminát", "silikon", "beton",
                    "polystyren", "guma syntetická", "akryl"],
        "asks": ["jsou přírodního původu", "vyrábějí se z nich věci", "dají se koupit v metráži nebo na váhu"],
    },
    {
        "id": "jidlo-pecene",
        "roof": "jídla",
        "level": "hard",
        "inside": ["chleba", "houska", "rohlík", "koláč", "buchta", "štrúdl",
                   "bábovka", "perník", "vánočka", "croissant"],
        "outside": ["knedlík", "halušky", "noky", "těstoviny", "palačinka",
                    "lívanec", "koblih", "smažený sýr"],
        "asks": ["pečou se v troubě", "dělají se z těsta", "dají se koupit v obchodě"],
    },
    {
        "id": "vesmir-hvezdy",
        "roof": "vesmírná tělesa a jevy",
        "level": "hard",
        "inside": ["Slunce", "Sirius", "Polárka", "Betelgeuze", "Vega", "Antares"],
        "outside": ["Měsíc", "Mars", "Halleyova kometa", "Mléčná dráha", "asteroid",
                    "meteorit", "černá díra", "mlhovina"],
        "asks": ["jsou to hvězdy", "vidíme je na obloze", "jsou od nás daleko"],
    },
    {
        "id": "hry-karty",
        "roof": "hry",
        "level": "easy",
        "inside": ["mariáš", "žolík", "prší", "poker", "canasta", "bridž", "voko",
                   "kanasta", "solitér"],
        "outside": ["dáma", "šachy", "člověče, nezlob se", "domino", "kostky",
                    "scrabble", "kuželky", "puzzle"],
        "asks": ["hrají se s kartami", "jsou to hry pro víc lidí", "dají se hrát u stolu"],
    },
    {
        "id": "telo-parove",
        "roof": "části lidského těla",
        "level": "normal",
        "inside": ["oko", "ucho", "ruka", "noha", "ledvina", "plíce", "koleno",
                   "loket", "rameno", "chodidlo"],
        "outside": ["srdce", "jazyk", "nos", "žaludek", "játra", "slezina",
                    "mozek", "pupek", "brada", "krk"],
        "asks": ["máme je v páru", "jsou to části těla", "dají se pojmenovat i u zvířat"],
    },
    {
        "id": "doprava-koleje",
        "roof": "dopravní prostředky",
        "level": "easy",
        "inside": ["vlak", "tramvaj", "metro", "lanovka pozemní", "důlní vozík",
                   "rychlík", "lokomotiva"],
        "outside": ["autobus", "trolejbus", "auto", "kolo", "loď", "letadlo",
                    "koloběžka", "traktor", "motorka"],
        "asks": ["jezdí po kolejích", "vozí lidi nebo náklad", "mají řidiče nebo strojvedoucího"],
    },
    {
        "id": "nastroje-dilna",
        "roof": "nářadí",
        "level": "hard",
        "inside": ["kladivo", "palice", "sekera", "majzlík", "sekáč", "perlík"],
        "outside": ["pilník", "šroubovák", "kleště", "pila", "vrtačka", "hoblík",
                    "svěrák", "měřicí pásmo", "klíč"],
        "asks": ["pracují úderem", "patří do dílny", "mají násadu nebo rukojeť"],
    },
    {
        "id": "pocasi-srazky",
        "roof": "počasí",
        "level": "normal",
        "inside": ["déšť", "sníh", "kroupy", "mrholení", "krupky", "mlha mrznoucí",
                   "liják", "přeháňka"],
        "outside": ["vítr", "mlha", "mráz", "vedro", "dusno", "obleva", "jinovatka",
                    "bouře", "zataženo"],
        "asks": ["padají z oblohy", "je to počasí", "hlásí je předpověď"],
    },
    {
        "id": "mena-euro",
        "roof": "měny",
        "level": "hard",
        "inside": ["euro", "šilink", "marka", "frank", "lira", "peseta", "drachma",
                   "escudo", "gulden"],
        "outside": ["koruna", "zlotý", "forint", "libra", "rubl", "dolar", "jen",
                    "švédská koruna", "leva"],
        "asks": ["nahradilo je euro nebo jím jsou", "jsou to měny", "platilo se jimi v Evropě"],
    },
]
